tracker_controllers:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  #front_flipper_joint_position_controller:
  #  type: effort_controllers/JointPositionController
  #  joint: front_flipper_joint
  #  pid: {p: 10000.0, i: 0.01, d: 10.0}
  #rear_flipper_joint_position_controller:
  #  type: effort_controllers/JointPositionController
  #  joint: rear_flipper_joint
  #  pid: {p: 10000.0, i: 0.01, d: 10.0}
  #arm_joint_0_joint_position_controller:
  #  type: effort_controllers/JointPositionController
  #  joint: arm_joint_0
  #  pid: {p: 1000.0, i: 0.01, d: 10.0}
  #arm_joint_1_joint_position_controller:
  #  type: effort_controllers/JointPositionController
  #  joint: arm_joint_1
  #  pid: {p: 1000.0, i: 0.01, d: 10.0}
  #arm_joint_2_joint_position_controller:
  #  type: effort_controllers/JointPositionController
  #  joint: arm_joint_2
  #  pid: {p: 1000.0, i: 0.01, d: 10.0}
  #arm_joint_3_joint_position_controller:
  #  type: effort_controllers/JointPositionController
  #  joint: arm_joint_3
  #  pid: {p: 1000.0, i: 0.01, d: 10.0}
  #front_spinning_lidar_spin_joint_velocity_controller:
  #  type: effort_controllers/JointVelocityController
  #  joint: front_spinning_lidar_spin_joint
  #  pid: {p: 0.4, i: 0.0, d: 0.0}
  #rear_spinning_lidar_spin_joint_velocity_controller:
  #  type: effort_controllers/JointVelocityController
  #  joint: rear_spinning_lidar_spin_joint
  #  pid: {p: 0.4, i: 0.0, d: 0.0}


  arm_traj_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - arm_joint_0
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      #- arm_joint_4

    gains: # Required because we're controlling an effort interface
      arm_joint_0: {p: &kp_default 16000,  d: &kd_default 5.0, i: &ki_default 2, i_clamp: &ki__clamp_default 2}
      arm_joint_1: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      arm_joint_2: {p: *kp_default,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      arm_joint_3: {p: 6000       ,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}
      #arm_joint_4: {p: 6000      ,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}

    constraints:
      goal_time: &goal_time_constraint 4.0
      stopped_velocity_tolerance: 1.0
      arm_joint_0:
        goal: &goal_pos_constraint 0.5
        trajectory: &trajectory_pos_constraint 1.0
      arm_joint_1:
        goal: *goal_pos_constraint
        trajectory: *trajectory_pos_constraint
      arm_joint_2:
        goal: *goal_pos_constraint
        trajectory: *trajectory_pos_constraint
      arm_joint_3:
        goal: *goal_pos_constraint
        trajectory: *trajectory_pos_constraint
      #arm_joint_4:
      #  goal: *goal_pos_constraint
      #  trajectory: *trajectory_pos_constraint

    stop_trajectory_duration: 1.0

  #flipper_traj_controller:
  #    type: "effort_controllers/JointTrajectoryController"
  #    joints:
  #      - front_flipper_joint
  #      - rear_flipper_joint

  #    gains: # Required because we're controlling an effort interface
  #      front_flipper_joint: {p: 10000,  d: *kd_default, i: *ki_default, i_clamp: *ki__clamp_default}
  #      rear_flipper_joint: {p: 10000,  d: *kd_default , i: *ki_default, i_clamp: *ki__clamp_default}

  #    constraints:
  #      goal_time: *goal_time_constraint
  #      stopped_velocity_tolerance: 1.0
  #      front_flipper_joint:
  #        goal: *goal_pos_constraint
  #        trajectory: *trajectory_pos_constraint
  #      rear_flipper_joint:
  #        goal: *goal_pos_constraint
  #        trajectory: *trajectory_pos_constraint

  #    stop_trajectory_duration: 1.0
